#!/usr/bin/env python3

import fileinput
import humanize

for line in fileinput.input():
    compressedSize, slash, origSize = tuple(line.split())
    print ('{0} {1} {2:>9}'.format(humanize.naturalsize(compressedSize, gnu=True),slash,humanize.naturalsize(origSize, gnu=True)))